### PR TITLE
New notion lib

### LINKED ISSUE #22: Try notion-ruby-client lib

### PR DESCRIPTION
**Pull request by dealingwith**

### CODE REVIEW

**Comment by dealingwith** [comment]
@jamespeilunli this is branched off of #21 's branch, hence the extra commits. They should go away after 21 is merged and this branch is rebased.

**Comment by dealingwith** [comment]
@jamespeilunli welp, the good news is we get a lot more data in the original search API call, the bad news is I can't store it all in the session because I run out of room 😦 

Might need to look into server-side session solutions (probably Redis) again

**Comment by dealingwith** [comment]
@jamespeilunli I pushed all the changes to make the new Ruby lib work. I haven't been able to get completing tasks to work with the new lib yet, so I just commented out all that code for now.

I'm not sure why this PR has other commits on it 😕

**Comment by dealingwith** [comment]
@jamespeilunli And I had to add server-side session management via https://github.com/moneta-rb/moneta, which will also allow us to easily use Redis or some other NoSQL data store in the future. For now the session data is just stored in memory so it still clears every time the app is restarted. But this is more reliable than the cookie storage, which was running out of storage space with all the new data I needed to store in session with the new library.

**Comment by dealingwith** [comment]
https://developers.notion.com/reference/patch-page is what I need to look at more carefully to get complete task to work again. But even the way it was working, it only supported "select" fields and it always wanted to set it to "Done", which is very specific to my personal tasks database. Actually making that flexible will be a considerable amount of work.

**Review by jamespeilunli — APPROVED** [review]

**Pull request merged**
