### PR TITLE
first pass at Notion OAuth

### PR DESCRIPTION
**Pull request by dealingwith**
- [x] Get TaskSheet running locally again
- [x] Confirm issue 42 is complete and either close or write follow-up ticket(s)
- [x] Set up Notion for OAuth
- [x] Get ngrok running locally under my account
- [x] Configure Notion OAuth for ngrok
- [x] Store token in session
- [x] Success!
- [ ] Figure out how we’re going to persist user tokens (new ticket)
- [ ] Update the database picker (new ticket)

### CODE REVIEW

**Comment by dealingwith** [comment]
https://www.notion.so/my-integrations

**Comment by dealingwith** [comment]
https://lostisland.github.io/faraday/

**Comment by dealingwith** [comment]
https://stackoverflow.com/questions/67782515/notion-api-getting-invalid-grant-when-trying-to-generate-authorization-token

**Comment by dealingwith** [comment]
Had to update the notion API gem to get it to play well with Faraday. Required deleting `Gemfile.lock` and re-running `bundle`. Got us from `1.0` to `1.2.1`.

**Comment by dealingwith** [comment]
I also put Faraday in front of the Notion API gem in the Gemfile, so I'm not actually sure which fixed the conflict, but happy to get a more up-to-date version of the Notion API gem regardless.

**Comment by dealingwith** [comment]
https://developers.notion.com/docs/authorization

**Comment by dealingwith** [comment]
Testing:

- run `ngrok http 4567`
- copy the ngrok URL
- put that into config.rb as `NGROK_URL`
- put that into the Notion integration settings (currently only Daniel can do this)
- start the Sinatra server
- go to the URL that ngrok generates and is shown in the terminal
- click to blue button on that page
- click on Log in with Notion
- give Tasksheet permission on databases
- continue as normal

**Review by jamespeilunli — APPROVED** [review]

**Pull request merged**
