### PR TITLE
Add multifilter filters to web app

### LINKED ISSUE #20: Support a user-chosen array of filter options in web app

### PR DESCRIPTION
**Pull request by dealingwith**
resolves #20

### CODE REVIEW

**Comment by dealingwith** [comment]
I've been unable to get the "status" type to work so even though the code could support filtering by the "status" type, I still only support the "select" type in this branch.

​In my attempts to get a query to work with the "status" type, I tested in Postman and was successful.
Then I started to get suspicious that it might be the Ruby library we're using for Notion API interaction.
I found a different, better, and more frequently updated Notion Ruby library, and tested with it. It worked. https://github.com/orbit-love/notion-ruby-client
I still haven't tested our original library with a simple by-hand query, but I like this newly-found library so much more I think I'm going to try to refactor our project to use it.

**Comment by jamespeilunli** [comment]
The atomic commits were helpful.

When I was testing the code by going through the config process and got to `/?filter_options=Done`, it displayed this (irrelevant information replaced with "..."):
```
Message: Session is empty: ...

DB ID: ...

filter_property: Status

filter_type: select

filter_options:
```
I believe this is what happened: the `# if filter_option was not passed in, and does not exist in session, try grabbing it from the config` block was executed due to `session[:filter_options]` being nil, but `CONFIG['filter_options']` was nil, so `session[:filter_options]` was reassigned to nil when it was assigned to `CONFIG['filter_options']`. Then, the `# else, things have gone wrong` block was executed, giving the error. 

A fix for this is that works is to check `if (params[:filter_option])`, and then `elsif (defined?(CONFIG) && session[:filter_options].nil?)`, letting the param filter option have priority over the config filter option, instead of the other way around.

This presents a general problem: what should we do if the user defines `CONFIG` but does not fill in the required information (like what I did)? I assume this problem will be apparent if/when we add more `CONFIG` options.

**Comment by jamespeilunli** [comment]
I'll check out the "status" type issue and the newly-found library tomorrow, thanks for letting me know.

**Comment by dealingwith** [comment]
@jamespeilunli great catch on the logic around passed-in vars vs config vars. I'll look into it.

I pushed a branch with some new lib implementation. I'll create a draft PR so you can check it out. The great news is the search API returns a bunch more information that will prevent additional API calls for properties and filter options. The bad news is it will be a decent-sized refactor.

**Comment by dealingwith** [comment]
I won't have time to return to this until later this afternoon. My plan will be: fix this PR to address what you found, get it merged, rebase the new lib branch, continue with that refactor.

**Comment by dealingwith** [comment]
@jamespeilunli pushed a new config with different branching logic in the `/` route that should better handle various ways of getting all the data needed

> This presents a general problem: what should we do if the user defines CONFIG but does not fill in the required information (like what I did)? I assume this problem will be apparent if/when we add more CONFIG options.

I think if someone is using `config.rb` then they can be expected to figure out what needs to be in there.

**Review by jamespeilunli — APPROVED** [review]
Looks good!

**Pull request merged**
